plugins {
    id 'org.springframework.boot' version '3.2.2'
    id 'java'
}

group = 'gr.aueb.lecturelens'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb:3.2.2'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.2.2'
    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.2.2'
}

tasks.named('test') {
    useJUnitPlatform()
}
